site_name: ゆかりねっとコネクターNEO
theme:
  name: material
  language: ja
  features:
    - content.tabs.link
  font:
    text: BIZ UDPGothic
  palette:
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: ライトモードに切り替えます。
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      scheme: default      
      toggle:
          #icon: material/toggle-switch-off-outline
          icon: material/brightness-7 
          name: ダークモードに切り替えます。
    - media: "(prefers-color-scheme: dark)"            
      primary: blue
      accent: blue
      scheme: slate
      toggle:
          #icon: material/toggle-switch
          icon: material/brightness-4 
          name: オートモードに切り替えます。
extra:
  search:
    language: 'ja'
markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - fontawesome_markdown
  - codehilite
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    
  - pymdownx.highlight:
      anchor_linenums: true
extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
plugins:
  - git-revision-date-localized
nav:
    - 概要: 'index.md'
    - ダウンロード: 'download.md'
    - できること: 'spec.md'
    - 攻略手順(チートシート):
      - 最速で英語翻訳をだす : 'cs_en.md'
      - OBS Studioできれいに出す: 'cs_obs.md'
      - コラボ字幕(Discord経由): 'cs_colab_discord.md'
      - コラボ字幕(UDトーク経由): 'cs_colab_udtalk.md'
      - StreamDeckで操作する : 'cs_streamdeck.md'
    - 設定について:
      - 標準設定項目: 'startup_basic.md'      
      - オプション設定: 'startup_option.md'
    - 支援について:
      - 支援の概要: 'support_summary.md'
      - 支援の仕方: 'support_howto.md'
      - 支援機能の有効化: 'support_enabled_md'    
    - プラグイン:    
      - 読み上げ:    
        - 棒読みちゃん連携: 'plugin_bouyomi.md'
        - Softalk読み上げ: 'plugin_softalk.md'
        - 読み上げ : 'plugin_playvoice.md'
      - サウンド:
        - 動画再生 : 'plugin_MediaPlayer.md'      
        - 音源再生 : 'plugin_playsound.md'
      - 認識の修正:
        - 辞書 : 'plugin_dictionary.md'
        - 正規表現 : 'plugin_regexp.md'
      - 見た目の補正:
        - 強制整形 : 'plugin_forcestyle.md'
        - ルビ付与 : 'plugin_ruby'
      - 表示関連:
        - 内蔵ブラウザ: 'plugin_browser.md'
        - 歌詞支援 : 'plugin_LyricAssist.md'
        - フォト読み込み : 'plugin_photopickup.md'
        - 表示拡張(スタンプ) : 'plugin_viewextend.md'
      - Windows連携:
        - クリップボード連携: 'plugin_clipboard.md'
        - MIDI入力 : 'plugin_midiinput.md'
      - 配信システム:
        - コメジェネ連携: 'plugin_commentgen.md'
        - 配信ソフト向けテキスト出力 : 'plugin_OBSFile.md'
        - OBS連携 WSv4 : 'plugin_OBS.md'
        - OBS連携 WSv5 : 'plugin_OBS5.md'
      - アプリ連携:
        - わんコメテンプレ連携 : 'plugin_OCTemplateGen.md'
        - 翻訳・発話連携 : 'plugin_transSrv.md'
        - バーチャルキャスト連携 : 'plugin_vcas.md'
        - VaNiiツール連携 : 'plugin_vanii.md'
        - VRChat OSC連携: 'plugin_vrchat_osc.md'
        - VRオーバーレイ : 'plugin_vroverlay.md'
        - ばもきゃ連携 : 'plugin_vmc.md'
        - MTGカード支援 : 'plugin_MTGCard.md'
      - サイト連携:
        - Discord BOT連携 : 'plugin_dicord.md'
        - Discord Webhook連携 : 'plugin_dicordwebhook.md'
        - Twitchチャット連携: 'plugin_twitch.md'
        - Youtube Live字幕送信: 'plugin_youtube.md'
        - Youtubeタイムコード生成 : 'plugin_youtubetimecode.md'
        - ZOOM連携 : 'plugin_zoom.md'
      - つかいやすさ向上:
        - 直接入力: 'plugin_directinput.md'
        - 入力支援 : 'plugin_InputAssist.md'
        - 起動支援 : 'plugin_startup.md'
        - アップデート通知 : 'plugin_update.md'
        - ファイル出力 : 'plugin_exporter.md'
    - アンバサダープログラム:
      - 1期生: 'ambasador_gen1.md'
    - サポータ: 'supporter.md'
    - 活用に関する補足・注意点: 'system_info.md'
    - 困ったときは:
      - よくある質問 : 'faq.md'
      - 再インストール : 'reinstall.md'
      - 不具合を発見した時 : 'report.md'
      - ヘルプを頼む前に : 'before_help.md' 
    - 技術者向け:
      - 連携について : 'tech.md'

