site_name: ゆかりねっとコネクターNEO
theme:
  name: material
  language: ja
  features:
    - tabs
  palette:
    primary: indigo
    accent: indigo
extra:
  search:
    language: 'ja'
markdown_extensions:
    - admonition
    - fontawesome_markdown
    - codehilite
    - pymdownx.emoji
        - emoji_generator: !!python/name:pymdownx.emoji.to_svg
extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
plugins:
  - git-revision-date-localized
nav:
    - Home: 'index.md'
