site_name: ゆかりねっとコネクターNEO
theme:
  name: material
  language: ja
  features:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
extra:
  search:
    language: 'ja'
markdown_extensions:
    - admonition
    - fontawesome_markdown
    - codehilite
    - pymdownx.emoji
    - attr_list
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.details
    - admonition
extra_css:
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
plugins:
  - git-revision-date-localized
nav:
    - 概要: 'index.md'
    - ダウンロード: 'download.md'
